gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - underline
    # selectedRangeBgColor:
    #   - underline

git:
  paging:
    colorArg: always
    # pager: delta --dark --paging=never --line-numbers --side-by-side
    pager: delta --dark --paging=never --line-numbers
